//! Perceptual weighting filter coefficient calculator (block 38 of
//! Figure 4a/G.728), §3.3 / §3.4 of the Recommendation.
//!
//! ## Scope
//!
//! The encoder runs a 10th-order pole-zero perceptual weighting filter
//! `W(z)` on input speech (block 4) and on the zero-input response
//! generated by the synthesis filter (block 10). §3.3 defines the
//! filter as
//!
//! ```text
//!         Q̃(z / γ₁)
//! W(z) = ────────────                                            (3-4a)
//!         Q̃(z / γ₂)
//! ```
//!
//! where `Q̃(z) = 1 + Σᵢ qᵢ · z⁻ⁱ` (eq. 3-3a with `q₀ = 1`) is the
//! 10th-order prediction-error filter built from the order-10 LPC
//! predictor coefficients `qᵢ` produced by the Levinson-Durbin recursion
//! of block 37 (`q_i = a_i^{(10)}`, eq. 3-2f), and `γ₁ = WZCF = 0.9`,
//! `γ₂ = WPCF = 0.6` are the spec-paragraph zero-control and
//! pole-control bandwidth factors of Table 1/G.728.
//!
//! Block 38 expands the substitutions `z ← z/γ₁` and `z ← z/γ₂`
//! mechanically:
//!
//! ```text
//! Q̃(z/γ₁) = 1 + Σᵢ (qᵢ · γ₁ⁱ) · z⁻ⁱ                            (3-4b)
//! Q̃(z/γ₂) = 1 + Σᵢ (qᵢ · γ₂ⁱ) · z⁻ⁱ                            (3-4c)
//! ```
//!
//! i.e. the bandwidth-broadened sequences `qᵢ·γ₁ⁱ` (numerator) and
//! `qᵢ·γ₂ⁱ` (denominator) for `i = 1..=10`. The leading taps `i = 0`
//! are both `1` by construction of `Q̃(z)` and are not stored.
//!
//! ## Output layout
//!
//! Both the numerator and the denominator are written in the standard
//! "spec 1-based" layout: index 0 carries the implicit unity tap
//! (`q₀ · γ_k⁰ = 1`), and indices `1..=LPCW` carry the broadened
//! coefficients. This matches the [`crate::SynthesisAdapter::coefficients`]
//! layout already in use elsewhere in the crate, so the weighting
//! filter can be applied with the same "skip element 0, dot product
//! over 1..=LPCW" idiom.
//!
//! ## Non-speech mode
//!
//! §3.4.1 specifies that for modem signals / other non-speech signals
//! the encoder is permitted to disable the weighting filter by setting
//! `W(z) = 1`. The spec note says this is achievable by setting `γ₁`
//! and `γ₂` to zero — that drops every non-unity tap of both the
//! numerator and the denominator to zero and the filter degenerates to
//! `1 / 1 = 1`. The [`WeightingFilterCoeff::disabled`] constructor
//! returns exactly this `(γ₁, γ₂) = (0, 0)` state without going
//! through the full transform.
//!
//! ## Scope of round 248
//!
//! This module lands only the transform `q_i → (qγ₁_i, qγ₂_i)` and a
//! thin accessor on the [`crate::Encoder`]. Block 4 / block 10
//! (the weighting filter applied to input speech / to the zero-input
//! response of the synthesis filter) is intentionally NOT wired up —
//! that has its own per-vector delay-line state plus the special
//! initialisation rule of §3.4 ("filter memory should not be reset to
//! zero at any time except during initialisation"), which is a
//! separate concern from the coefficient calculator.

use crate::consts::{LPCW, WPCF, WZCF};

/// Output of block 38 — the two 10th-order coefficient vectors for
/// `W(z) = Q̃(z/γ₁) / Q̃(z/γ₂)`.
///
/// Both fields use the spec's 1-based layout: index 0 is the implicit
/// `q_0 · γ_k^0 = 1` leading tap; indices `1..=LPCW` carry the
/// bandwidth-broadened predictor coefficients.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct WeightingFilterCoeff {
    /// Numerator coefficients `qγ₁_i` for `i = 0..=LPCW`.
    /// `q_gamma1[0] = 1.0` (implicit leading tap of `Q̃`).
    /// `q_gamma1[i] = q_i · γ₁ⁱ` for `i = 1..=LPCW` (eq. 3-4b).
    pub q_gamma1: [f64; LPCW + 1],
    /// Denominator coefficients `qγ₂_i` for `i = 0..=LPCW`.
    /// `q_gamma2[0] = 1.0` (implicit leading tap of `Q̃`).
    /// `q_gamma2[i] = q_i · γ₂ⁱ` for `i = 1..=LPCW` (eq. 3-4c).
    pub q_gamma2: [f64; LPCW + 1],
}

impl Default for WeightingFilterCoeff {
    /// Fresh state — both sequences degenerate to the all-pass
    /// `1 / 1`, i.e. `W(z) = 1`. Identical to [`Self::disabled`] and
    /// to the §3.4.1 non-speech mode.
    fn default() -> Self {
        Self::disabled()
    }
}

impl WeightingFilterCoeff {
    /// Construct the `W(z) = 1` (filter disabled) state. This is the
    /// initial value before the first adaptation cycle has produced
    /// `q_i`, and is also the §3.4.1 non-speech-mode value (set
    /// `γ₁ = γ₂ = 0`, which drops every non-unity tap).
    pub const fn disabled() -> Self {
        let mut q_gamma1 = [0.0; LPCW + 1];
        let mut q_gamma2 = [0.0; LPCW + 1];
        // Eq. 3-3a leading tap `q_0 = 1`; carries through unchanged.
        q_gamma1[0] = 1.0;
        q_gamma2[0] = 1.0;
        Self { q_gamma1, q_gamma2 }
    }

    /// Block 38: derive the weighting filter coefficients from the
    /// order-10 LPC predictor coefficients `q_i` (eq. 3-3 with
    /// `q_0 = 1`).
    ///
    /// `q` must be in the same 1-based layout as the rest of the crate:
    /// `q[0]` carries the spec's `q_0 = 1` (verified at compute time)
    /// and `q[1..=LPCW]` carry the predictor coefficients output by
    /// block 37.
    ///
    /// The output uses the spec-default `γ₁ = WZCF = 0.9` and
    /// `γ₂ = WPCF = 0.6` of Table 1/G.728. For the §3.4.1 non-speech
    /// disabled path, use [`Self::disabled`] directly.
    ///
    /// # Panics
    ///
    /// Panics if `q[0] != 1.0` — the spec's `q_0 = 1` invariant is the
    /// definition of the prediction-error filter `Q̃(z)` (eq. 3-3a).
    pub fn from_lpc(q: &[f64; LPCW + 1]) -> Self {
        Self::from_lpc_with_gammas(q, WZCF, WPCF)
    }

    /// Same as [`Self::from_lpc`] but with caller-supplied `γ₁` /
    /// `γ₂` bandwidth factors. Exposed primarily for the §3.4.1
    /// disabled-mode path (`γ₁ = γ₂ = 0`) and for the unit tests; the
    /// production encoder always uses [`Self::from_lpc`].
    pub fn from_lpc_with_gammas(q: &[f64; LPCW + 1], gamma1: f64, gamma2: f64) -> Self {
        // Spec invariant of Q̃(z), eq. 3-3a: q_0 = 1 by definition.
        // Bake it in here rather than silently overriding the caller's
        // q[0] — a non-unity q[0] would mean the upstream Levinson
        // recursion broke the spec's leading-tap convention.
        assert_eq!(
            q[0], 1.0,
            "Q̃(z) requires q_0 = 1 (eq. 3-3a); got q[0] = {}",
            q[0]
        );

        let mut q_gamma1 = [0.0f64; LPCW + 1];
        let mut q_gamma2 = [0.0f64; LPCW + 1];

        // Eq. 3-3a leading tap. q_0 · γ_k^0 = 1 for either γ_k.
        q_gamma1[0] = 1.0;
        q_gamma2[0] = 1.0;

        // Eq. 3-4b / 3-4c: q_i · γ_k^i. We accumulate γ_k^i across the
        // loop rather than calling powi() each iteration so a
        // future fixed-point pass can mirror the same shape.
        let mut g1_pow_i = 1.0; // γ₁⁰
        let mut g2_pow_i = 1.0; // γ₂⁰
        for i in 1..=LPCW {
            g1_pow_i *= gamma1;
            g2_pow_i *= gamma2;
            q_gamma1[i] = q[i] * g1_pow_i;
            q_gamma2[i] = q[i] * g2_pow_i;
        }

        Self { q_gamma1, q_gamma2 }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn disabled_state_is_w_of_z_equals_one() {
        // §3.4.1: the filter is "disabled" when both numerator and
        // denominator collapse to the all-pass 1. Confirm the
        // leading taps are 1 and every non-unity tap is exactly zero.
        let coeff = WeightingFilterCoeff::disabled();
        assert_eq!(coeff.q_gamma1[0], 1.0);
        assert_eq!(coeff.q_gamma2[0], 1.0);
        for i in 1..=LPCW {
            assert_eq!(coeff.q_gamma1[i], 0.0, "γ₁ tap {} non-zero", i);
            assert_eq!(coeff.q_gamma2[i], 0.0, "γ₂ tap {} non-zero", i);
        }
    }

    #[test]
    fn default_matches_disabled() {
        // The Default impl is the §3.4.1 non-speech-mode value.
        assert_eq!(
            WeightingFilterCoeff::default(),
            WeightingFilterCoeff::disabled()
        );
    }

    #[test]
    fn unity_q_yields_geometric_progression() {
        // Drive the calculator with q_i = 1 for every tap; the output
        // should be the literal γ₁^i / γ₂^i geometric progressions
        // (sanity check that nothing else is being multiplied in
        // somewhere — confirms the eq. 3-4b/c shape against a
        // hand-traceable input).
        let q = [1.0f64; LPCW + 1];
        let coeff = WeightingFilterCoeff::from_lpc(&q);

        let mut g1 = 1.0f64; // γ₁⁰
        let mut g2 = 1.0f64; // γ₂⁰
        for i in 0..=LPCW {
            // i = 0 case: γ_k⁰ = 1 → coeff = 1. Subsequent iterations
            // multiply by γ_k once each.
            assert!(
                (coeff.q_gamma1[i] - g1).abs() < 1e-14,
                "q_gamma1[{}] = {} vs γ₁^{} = {}",
                i,
                coeff.q_gamma1[i],
                i,
                g1
            );
            assert!(
                (coeff.q_gamma2[i] - g2).abs() < 1e-14,
                "q_gamma2[{}] = {} vs γ₂^{} = {}",
                i,
                coeff.q_gamma2[i],
                i,
                g2
            );
            g1 *= WZCF;
            g2 *= WPCF;
        }
    }

    #[test]
    fn zero_gammas_disable_filter() {
        // §3.4.1: setting γ₁ = γ₂ = 0 turns block 4 / block 10 into
        // pass-throughs because every non-unity tap drops out. Run
        // the full transform with an arbitrary q_i and confirm only
        // the leading tap survives.
        let q = [
            1.0f64, 0.7, -0.3, 0.2, -0.15, 0.1, -0.08, 0.06, -0.04, 0.02, -0.01,
        ];
        let coeff = WeightingFilterCoeff::from_lpc_with_gammas(&q, 0.0, 0.0);

        assert_eq!(coeff.q_gamma1[0], 1.0);
        assert_eq!(coeff.q_gamma2[0], 1.0);
        for i in 1..=LPCW {
            assert_eq!(coeff.q_gamma1[i], 0.0);
            assert_eq!(coeff.q_gamma2[i], 0.0);
        }
    }

    #[test]
    fn known_lpc_matches_eq_3_4b_3_4c_termwise() {
        // Hand-trace eq. 3-4b/3-4c on a small known q_i vector and
        // compare term-by-term. Uses the spec γ₁ = 0.9, γ₂ = 0.6.
        let q = [
            1.0f64,
            0.5,
            -0.25,
            0.125,
            -0.0625,
            0.03125,
            -0.015_625,
            0.007_812_5,
            -0.003_906_25,
            0.001_953_125,
            -0.000_976_562_5,
        ];
        let coeff = WeightingFilterCoeff::from_lpc(&q);

        // Termwise expected values from eq. 3-4b / 3-4c:
        //   qγ₁_i = q_i · 0.9^i
        //   qγ₂_i = q_i · 0.6^i
        for i in 0..=LPCW {
            let expected_g1 = q[i] * WZCF.powi(i as i32);
            let expected_g2 = q[i] * WPCF.powi(i as i32);
            assert!(
                (coeff.q_gamma1[i] - expected_g1).abs() < 1e-14,
                "q_gamma1[{}] = {} vs hand value {} (diff {})",
                i,
                coeff.q_gamma1[i],
                expected_g1,
                (coeff.q_gamma1[i] - expected_g1).abs()
            );
            assert!(
                (coeff.q_gamma2[i] - expected_g2).abs() < 1e-14,
                "q_gamma2[{}] = {} vs hand value {} (diff {})",
                i,
                coeff.q_gamma2[i],
                expected_g2,
                (coeff.q_gamma2[i] - expected_g2).abs()
            );
        }
    }

    #[test]
    fn poles_radii_shrink_more_than_zeros() {
        // §3.4 / §3.7 invariant: γ₂ < γ₁ < 1 → the denominator's poles
        // are pulled closer to the origin than the numerator's zeros,
        // which is what produces W(z)'s perceptual "spectral
        // de-emphasis" character (the formant peaks are widened).
        // The Table-1/G.728 paragraph-value constants enforce the
        // ordering; this test exercises only the geometric
        // consequence: at i = LPCW the denominator coefficient is
        // closer to zero than the numerator's, for any q with
        // |q_i| > 0.
        const _: () = assert!(WPCF < WZCF);
        const _: () = assert!(WZCF < 1.0);

        let q = [1.0f64; LPCW + 1];
        let coeff = WeightingFilterCoeff::from_lpc(&q);
        assert!(coeff.q_gamma2[LPCW].abs() < coeff.q_gamma1[LPCW].abs());
    }

    #[test]
    #[should_panic(expected = "q_0 = 1")]
    fn non_unity_q0_panics() {
        // Eq. 3-3a is definitional: q_0 = 1. Driving the calculator
        // with a non-unity leading tap means the upstream Levinson
        // recursion violated the spec's leading-tap convention and is
        // not a state the encoder should ever be in. Surface that as
        // an assertion rather than silently truncating.
        let mut q = [1.0f64; LPCW + 1];
        q[0] = 2.0;
        let _ = WeightingFilterCoeff::from_lpc(&q);
    }
}
